
services:
  db:
    image: docker.arvancloud.ir/postgres:14
    environment:
      POSTGRES_USER: jewelry
      POSTGRES_PASSWORD: jewelry1234
      POSTGRES_DB: jewelry
    volumes:
      - ./db-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080

volumes:
  db-data:

